services:
  certbot_dns_duckdns:
    container_name: ${container_name}_certbot
    volumes:
      - $container_dir/certbot/letsencrypt:/etc/letsencrypt
      - $container_dir/certbot/log/letsencrypt:/var/log/letsencrypt
      - $container_dir/certbot/duckdns.ini:/conf/duckdns.ini
    image: infinityofspace/certbot_dns_duckdns:latest
    command: certonly --non-interactive --agree-tos --email <your-email>
      --preferred-challenges dns --authenticator dns-duckdns
      --dns-duckdns-credentials /conf/duckdns.ini
      --dns-duckdns-propagation-seconds 60 -d "$jks_domain"
  nginx:
    container_name: nginx
    build: ./ngnix .
    ports:
      - 80:80
      - 444:443
    volumes:
      - /home/ubuntu/nginx/config:/etc/nginx
      - /home/ubuntu/nginx/www:/var/www/html
      - /home/ubuntu/ngnix/ssl:/etc/nginx/ssl
  wowza:
    container_name: ${container_name}
    build: ./wowza .
